apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 27.0.2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  releaseName: traefik
  targetNamespace: traefik
  interval: 1m0s
  values:
    ingressRoute:
      dashboard:
        enabled: false
    resources:
      limits:
        cpu: 1000m
        memory: 600Mi
      requests:
        cpu: 200m
        memory: 200Mi
    redirectTo:
      port: websecure
    extraObjects: 
      - apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
            kubernetes.io/ingress.class: traefik
          labels:
            app: grafana
          name: grafana
          namespace: grafana
        spec:
          rules:
          - host: josephtest.andrena.io
            http:
              paths:
              - backend:
                  service:
                    name: grafana
                    port: 
                      number: 80
                path: /
                pathType: Prefix  
          tls:
          - hosts:
            - josephtest.andrena.io
            secretName: josephtest-tls